#!/usr/bin/env python3
"""Record the quest / story narration (Turkish + English) and embed it in src/narration-quests.js.
Source text: src/narration-quests-text.json  {key: {chapter, tr, en}}.
Turkish: tr-TR-AhmetNeural (same narrator as src/narration.js). English: en-US-SteffanNeural with the
dark-storyteller chain of tools/gen_english_voices.py. Leading/trailing silence trimmed with ffmpeg.
The output only ADDS keys to BABA.Narration / BABA.NarrationEN, so narration.js and narration-en.js stay untouched.
Run: python tools/gen_quest_voices.py   (needs edge-tts + ffmpeg)
"""
import asyncio, base64, hashlib, json, pathlib, re, shutil, subprocess, tempfile
import edge_tts
ROOT = pathlib.Path(__file__).resolve().parent.parent
TEXT = ROOT / 'src/narration-quests-text.json'
OUT = ROOT / 'src/narration-quests.js'
CACHE = pathlib.Path(tempfile.gettempdir()) / 'kabir-quest-voice-cache'
FFMPEG = shutil.which('ffmpeg') or 'ffmpeg'
TRIM = 'silenceremove=start_periods=1:start_threshold=-48dB:start_silence=0.035:detection=peak,areverse,silenceremove=start_periods=1:start_threshold=-48dB:start_silence=0.10:detection=peak,areverse,afade=t=in:d=0.006'
CONF = {
    'tr': ('tr-TR-AhmetNeural', '-10%', '-6Hz', TRIM + ',highpass=f=60,lowpass=f=7200,equalizer=f=120:t=q:w=0.9:g=4,aecho=0.8:0.85:70|150:0.18|0.1,alimiter=limit=0.92'),
    'en': ('en-US-SteffanNeural', '-20%', '-16Hz', TRIM + ',highpass=f=60,lowpass=f=6800,equalizer=f=120:t=q:w=0.9:g=5,equalizer=f=2800:t=q:w=1:g=-4,aecho=0.8:0.85:80|170:0.25|0.14,alimiter=limit=0.92'),
}
LINES = json.loads(TEXT.read_text(encoding='utf8'))

def spoken(text):
    return text.replace('. ', '... ').replace('? ', '?... ').replace(': ', ':... ')

def path(lang, text):
    return CACHE / (hashlib.sha256(json.dumps([lang, spoken(text), *CONF[lang]]).encode()).hexdigest() + '.mp3')

async def record(lang, key, text, sem):
    p = path(lang, text)
    if p.exists() and p.stat().st_size > 1000: return
    voice, rate, pitch, filters = CONF[lang]
    async with sem:
        for attempt in range(5):
            raw = p.with_suffix('.raw.mp3')
            try:
                await edge_tts.Communicate(spoken(text), voice, rate=rate, pitch=pitch).save(str(raw))
                subprocess.run([FFMPEG, '-y', '-loglevel', 'error', '-i', str(raw), '-af', filters, '-ac', '1', '-ar', '24000', '-c:a', 'libmp3lame', '-b:a', '48k', str(p)], check=True)
                raw.unlink(missing_ok=True)
                if p.stat().st_size < 1000: raise RuntimeError('empty')
                print('recorded', lang, key, flush=True); return
            except Exception as e:
                raw.unlink(missing_ok=True)
                if attempt == 4: raise RuntimeError(f'{lang}/{key}: {e}')
                await asyncio.sleep(2 * (attempt + 1))

def duration(p):
    r = subprocess.run([FFMPEG, '-i', str(p), '-f', 'null', '-'], capture_output=True, text=True)
    m = re.findall(r'time=(\d+):(\d+):([\d.]+)', r.stderr)[-1]
    return int(m[0]) * 3600 + int(m[1]) * 60 + float(m[2])

async def main():
    CACHE.mkdir(exist_ok=True)
    sem = asyncio.Semaphore(4)
    await asyncio.gather(*(record(lang, k, v[lang], sem) for k, v in LINES.items() for lang in ('tr', 'en')))
    out = {'tr': {}, 'en': {}}
    for k, v in LINES.items():
        for lang in ('tr', 'en'):
            p = path(lang, v[lang]); d = duration(p)
            if d < .25: raise RuntimeError(f'{lang}/{k}: too short')
            out[lang][k] = {'text': v[lang], 'speaker': 'Anlatıcı' if lang == 'tr' else 'Narrator', 'voice': CONF[lang][0], 'style': 'D',
                            'duration': round(d, 3), 'chapter': v.get('chapter', 0), 'audio': base64.b64encode(p.read_bytes()).decode()}
    body = ('// Generated by tools/gen_quest_voices.py from src/narration-quests-text.json (ajan:quests). Do not edit by hand.\n'
            '// Adds story/quest lines to BABA.Narration (tr-TR-AhmetNeural) and BABA.NarrationEN (en-US-SteffanNeural).\n'
            'window.BABA = window.BABA || {};\n(function (B) {\n'
            '  B.Narration = B.Narration || {}; B.NarrationEN = B.NarrationEN || {};\n'
            '  var TR = ' + json.dumps(out['tr'], ensure_ascii=False) + ';\n'
            '  var EN = ' + json.dumps(out['en'], ensure_ascii=False) + ';\n'
            '  Object.keys(TR).forEach(function (k) { if (!B.Narration[k]) B.Narration[k] = TR[k]; });\n'
            '  Object.keys(EN).forEach(function (k) { if (!B.NarrationEN[k]) B.NarrationEN[k] = EN[k]; });\n'
            '})(window.BABA);\n')
    OUT.write_text(body, encoding='utf8', newline='\n')
    print(f'WROTE {OUT.name}: {len(LINES)} lines x2, {OUT.stat().st_size} bytes', flush=True)

if __name__ == '__main__':
    asyncio.run(main())
