#!/usr/bin/env python3
"""Record chapter V's own lines (boss phases, the Black Qadi's challenge) and embed them in src/narration-finale.js.
Same chain as tools/gen_quest_voices.py (quests agent): Turkish tr-TR-AhmetNeural, English en-US-SteffanNeural, silence trimmed with ffmpeg.
The Qadi speaks lower and slower than the narrator. Only ADDS keys (never overwrites a key another file already defines).
Run: python tools/gen_finale_voices.py   (needs edge-tts + ffmpeg)
"""
import asyncio, base64, hashlib, json, pathlib, re, shutil, subprocess, tempfile
import edge_tts
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'src/narration-finale.js'
CACHE = pathlib.Path(tempfile.gettempdir()) / 'kabir-finale-voice-cache'
FFMPEG = shutil.which('ffmpeg') or 'ffmpeg'
TRIM = 'silenceremove=start_periods=1:start_threshold=-48dB:start_silence=0.035:detection=peak,areverse,silenceremove=start_periods=1:start_threshold=-48dB:start_silence=0.10:detection=peak,areverse,afade=t=in:d=0.006'
NARR = {
    'tr': ('tr-TR-AhmetNeural', '-10%', '-6Hz', TRIM + ',highpass=f=60,lowpass=f=7200,equalizer=f=120:t=q:w=0.9:g=4,aecho=0.8:0.85:70|150:0.18|0.1,alimiter=limit=0.92'),
    'en': ('en-US-SteffanNeural', '-20%', '-16Hz', TRIM + ',highpass=f=60,lowpass=f=6800,equalizer=f=120:t=q:w=0.9:g=5,equalizer=f=2800:t=q:w=1:g=-4,aecho=0.8:0.85:80|170:0.25|0.14,alimiter=limit=0.92'),
}
KADI = {
    'tr': ('tr-TR-AhmetNeural', '-22%', '-26Hz', TRIM + ',highpass=f=50,lowpass=f=6000,equalizer=f=100:t=q:w=0.9:g=6,aecho=0.8:0.9:110|260:0.3|0.18,alimiter=limit=0.92'),
    'en': ('en-US-SteffanNeural', '-26%', '-30Hz', TRIM + ',highpass=f=50,lowpass=f=5600,equalizer=f=100:t=q:w=0.9:g=7,aecho=0.8:0.9:120|280:0.32|0.2,alimiter=limit=0.92'),
}
LINES = {
    'ch5Kadi': {'who': 'kadi', 'tr': 'Kâtip. Kalemini bırakıp kaçtın; ama defter seni unutmadı. Son satır senin.',
                'en': 'Scribe. You dropped your quill and ran; but the ledger did not forget you. The last line is yours.'},
    'ch5Echo': {'who': 'narr', 'tr': 'Dört efendinin sesi onun ağzından konuşuyor. Hepsini bir kez daha yeneceksin.',
                'en': 'The four lords speak through his mouth. You will defeat them all once more.'},
    'ch5LastVerdict': {'who': 'kadi', 'tr': 'Hüküm okunuyor. Işığın kaldığı yerde dur; gerisi benim.',
                       'en': 'The verdict is being read. Stand where the light remains; the rest is mine.'},
}
SPEAKER = {'narr': ('Anlatıcı', 'Narrator'), 'kadi': ('Kara Kadı', 'The Black Qadi')}

def conf(who, lang): return (KADI if who == 'kadi' else NARR)[lang]
def spoken(text): return text.replace('. ', '... ').replace('; ', ';... ')
def path(who, lang, text): return CACHE / (hashlib.sha256(json.dumps([who, lang, spoken(text), *conf(who, lang)]).encode()).hexdigest() + '.mp3')

async def record(who, lang, key, text):
    p = path(who, lang, text)
    if p.exists() and p.stat().st_size > 1000: return
    voice, rate, pitch, filters = conf(who, lang)
    for attempt in range(5):
        raw = p.with_suffix('.raw.mp3')
        try:
            await edge_tts.Communicate(spoken(text), voice, rate=rate, pitch=pitch).save(str(raw))
            subprocess.run([FFMPEG, '-y', '-loglevel', 'error', '-i', str(raw), '-af', filters, '-ac', '1', '-ar', '24000', '-c:a', 'libmp3lame', '-b:a', '48k', str(p)], check=True)
            raw.unlink(missing_ok=True); print('recorded', lang, key, flush=True); return
        except Exception as e:
            raw.unlink(missing_ok=True)
            if attempt == 4: raise RuntimeError(f'{lang}/{key}: {e}')
            await asyncio.sleep(2 * (attempt + 1))

def duration(p):
    r = subprocess.run([FFMPEG, '-i', str(p), '-f', 'null', '-'], capture_output=True, text=True)
    m = re.findall(r'time=(\d+):(\d+):([\d.]+)', r.stderr)[-1]
    return int(m[0]) * 3600 + int(m[1]) * 60 + float(m[2])

async def main():
    CACHE.mkdir(exist_ok=True)
    await asyncio.gather(*(record(v['who'], lang, k, v[lang]) for k, v in LINES.items() for lang in ('tr', 'en')))
    out = {'tr': {}, 'en': {}}
    for k, v in LINES.items():
        for li, lang in enumerate(('tr', 'en')):
            p = path(v['who'], lang, v[lang])
            out[lang][k] = {'text': v[lang], 'speaker': SPEAKER[v['who']][li], 'voice': conf(v['who'], lang)[0], 'style': 'D', 'duration': round(duration(p), 3), 'chapter': 5,
                            'audio': base64.b64encode(p.read_bytes()).decode()}
    body = ('// Generated by tools/gen_finale_voices.py (ajan:chapter5). Do not edit by hand.\n'
            'window.BABA = window.BABA || {};\n(function (B) {\n'
            '  B.Narration = B.Narration || {}; B.NarrationEN = B.NarrationEN || {};\n'
            '  var TR = ' + json.dumps(out['tr'], ensure_ascii=False) + ';\n'
            '  var EN = ' + json.dumps(out['en'], ensure_ascii=False) + ';\n'
            '  Object.keys(TR).forEach(function (k) { if (!B.Narration[k]) B.Narration[k] = TR[k]; });\n'
            '  Object.keys(EN).forEach(function (k) { if (!B.NarrationEN[k]) B.NarrationEN[k] = EN[k]; });\n'
            '})(window.BABA);\n')
    OUT.write_text(body, encoding='utf8', newline='\n')
    print('WROTE', OUT.name, OUT.stat().st_size)

if __name__ == '__main__':
    asyncio.run(main())
